"""add_translation_settings_to_chats.

Revision ID: 0ec319cbc95e
Revises:
Create Date: 2026-04-22 23:49:22.610025

"""

from typing import TYPE_CHECKING

import sqlalchemy as sa

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "0ec319cbc95e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chats", sa.Column("target_lang", sa.String(), nullable=True))
    op.add_column("chats", sa.Column("ignored_langs", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chats", "ignored_langs")
    op.drop_column("chats", "target_lang")
    # ### end Alembic commands ###
