"""add encryption_salt to chats

Revision ID: a5097e6fe12d
Revises: 6e004f9c23cf
Create Date: 2026-05-15 20:17:28.976674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5097e6fe12d'
down_revision: Union[str, Sequence[str], None] = '6e004f9c23cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('encryption_salt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'encryption_salt')
    # ### end Alembic commands ###
